# Generated by Django 6.0.7 on 2026-08-05 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('avatar_color', models.CharField(default='#c5a059', max_length=20, verbose_name='Couleur Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('PAUSE', 'En pause'), ('REPOS', 'En repos'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10, verbose_name='Statut')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('pause_duration_minutes', models.IntegerField(default=0, verbose_name='Durée pause (min)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
