# Generated by Django 6.0.7 on 2026-08-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('READ', 'Lu'), ('PROCESSED', 'Traité')], default='NEW', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message Contact',
                'verbose_name_plural': 'Messages Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='Durée (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Compte Actif'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_team_member',
            field=models.BooleanField(default=True, verbose_name="Membre de l'Équipe (Statistiques)"),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employé'), ('MANAGER', 'Manager'), ('RESPONSABLE', 'Responsable'), ('VENDEUR', 'Vendeur'), ('LOGISTIQUE', 'Logistique'), ('ADMINISTRATEUR', 'Administrateur')], default='EMPLOYEE', max_length=50, verbose_name='Rôle Métier'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
