# Generated by Django 6.0.7 on 2026-08-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_product_service_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='pause_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Fin de pause'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='pause_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Début de pause'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='Salon', max_length=100, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Photo de Profil'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('ANNOUNCEMENT', 'Annonce'), ('ADMIN', "Message de l'administration"), ('SCHEDULE', 'Changement de planning')], default='ANNOUNCEMENT', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.employee', verbose_name='Employé (Vide = Tous)')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
