# Generated by Django 6.0.7 on 2026-08-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancerecord_pause_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_team_member',
            field=models.BooleanField(default=False, verbose_name="Membre de l'Équipe (Statistiques)"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('EMPLOYEE', 'Employé'), ('MANAGER', 'Manager'), ('RESPONSABLE', 'Responsable'), ('VENDEUR', 'Vendeur'), ('LOGISTIQUE', 'Logistique'), ('ADMINISTRATEUR', 'Administrateur')], default='USER', max_length=50, verbose_name='Rôle Métier'),
        ),
    ]
