# Generated by Django 6.0.7 on 2026-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shades',
            field=models.JSONField(blank=True, default=list, verbose_name='Nuances / Couleurs'),
        ),
    ]
