# Generated by Django 6.0.4 on 2026-08-12 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_shades'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Évaluation (1-5)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name="Commentaire d'évaluation"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('ARRIVED', 'Cliente arrivée'), ('IN_PROGRESS', 'Soin en cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Cliente absente')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='EmployeeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('title', models.CharField(default='Pause déjeuner', max_length=100, verbose_name='Libellé de la pause')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='core.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pause Employé',
                'verbose_name_plural': 'Pauses Employés',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
