# Generated by Django 6.0.4 on 2026-08-12 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reservation_rating_reservation_review_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sous-total (DH)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de livraison (DH)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Général (DH)')),
                ('delivery_mode', models.CharField(choices=[('DELIVERY', 'Livraison à domicile'), ('CLICK_COLLECT', 'Click & Collect')], default='DELIVERY', max_length=20, verbose_name='Mode de livraison')),
                ('payment_mode', models.CharField(choices=[('COD', 'Paiement à la livraison'), ('CARD', 'Carte bancaire'), ('STORE', 'Paiement au retrait')], default='COD', max_length=20, verbose_name='Mode de paiement')),
                ('order_status', models.CharField(choices=[('NEW', 'Nouvelle'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('SHIPPED', 'Expédiée'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='NEW', max_length=20, verbose_name='Statut commande')),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (DH)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Nuance / Variante')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total (DH)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
