# Generated by Django 6.0.4 on 2026-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('EMPLOYEE', 'Employé'), ('RECEPTION', 'Réceptionniste'), ('MANAGER', 'Manager'), ('RESPONSABLE', 'Responsable'), ('VENDEUR', 'Vendeur'), ('LOGISTIQUE', 'Logistique'), ('ADMINISTRATEUR', 'Administrateur')], default='USER', max_length=50, verbose_name='Rôle Métier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Nouvelle'), ('CONFIRMED', 'Confirmée'), ('PREPARING', 'En préparation'), ('READY_FOR_PICKUP', 'Prête au retrait'), ('RETRIEVED', 'Retirée'), ('SHIPPED', 'Expédiée'), ('DELIVERING', 'En livraison'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='NEW', max_length=20, verbose_name='Statut commande'),
        ),
    ]
