# Generated by Django 6.0.4 on 2026-08-13 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employee_role_alter_order_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée de la cliente"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Motif d'annulation"),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces 💵'), ('CARD', 'Carte bancaire 💳'), ('DIGITAL', 'Paiement électronique 📱')], default='CASH', max_length=20, verbose_name='Moyen de paiement')),
                ('status', models.CharField(choices=[('PENDING', 'En attente 🟡'), ('PAID', 'Payé 🟢'), ('REFUNDED', 'Remboursé 🔴')], default='PAID', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure du paiement')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.order', verbose_name='Commande')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
